### ISSUE TITLE
工数見積

### ISSUE THREAD

**Issue by tocoteron** [tokoroten-lab/engineer-ability-visualizer#7]
# 工数見積

とりあえず正常系だけを作る工数見積を行う

## 環境構築(3:00)

| 作業 | 想定時間(hh:mm) |
| ------------- | ------------- |
| DBのDocker環境構築 | 0:30 |
| バックエンドのDocker環境構築 | 1:00 |
| フロントエンドのDocker環境構築 | 1:00 |
| docker-composeで各環境を接続 | 0:30 |

## フロントエンド(4:40)

| 実装項目 | 想定時間(hh:mm) |
| ------------- | ------------- |
| ページの遷移ができる | 0:30 |
| エンジニアのログイン(GitHubアカウントとの連携) | 1:00 |
| 人事のログイン(メールアドレス/パスワード) | 1:00 |
| サービスに登録しているエンジニア一覧を表示する | 0:30 |
| 能力を可視化したいエンジニアのリストを管理できる(追加/削除/確認) | 1:00 |
| エンジニアの総合評価値を表示する | 0:30 |
| エンジニアの各評価値(内訳)を表示する | 0:30 |
| エンジニアの各評価値の計算方法を表示する | 0:30 |
| エンジニアの各評価値から何が分かるのかを表示する | 0:20 |
| エンジニアの評価値の推移を見れるようにする | 1:00 |

## バックエンド(12:00)

| 実装項目 | 想定時間(hh:mm) |
| ------------- | ------------- |
| GitHub APIからデータを取得する | 4:00 |
| エンジニアのログイン認証 | 1:00 |
| 人事のログイン認証 | 1:00 |
| 各評価項目の評価値を計算する | 3:00 |
| 各評価値をDBに保存する | 2:00 |
| エンジニアを分析対象のリストに追加する(DBに保存) | 1:00 |
| 分析対象の全てのエンジニアの各評価項目の評価値を定期的に収集する | 2:00 |

## DB(1:30)

| 作業 | 想定時間(hh:mm) |
| ------------- | ------------- |
| スキーマの設計 | 1:00 |
| テーブル定義のSQLファイル作成&DBにロード | 0:30 |

**Comment by tokoroten-lab** [comment]
## 環境構築

|  | 想定時間 |

## フロントエンド

| 実装項目 | 想定時間 |
| ------------- | ------------- |
| 能力を可視化したいエンジニアのGitHubアカウントをURLで指定できる | |
| 能力を可視化したいエンジニアのリストを管理できる(追加/削除/確認) | |
| エンジニアの総合評価値を表示する | |
| エンジニアの各評価値(内訳)を表示する | |
| エンジニアの各評価値の計算方法を表示する | |
| エンジニアの各評価値から何が分かるのかを表示する | |
| エンジニアの評価値の推移を見れるようにする | |

## バックエンド

| GitHub APIからデータを取得する | |
| 各評価項目の評価値を計算する | |
| 各評価値をDBに保存する | |
| エンジニアを分析対象のリストに追加する(DBに保存) | |
| 分析対象の全てのエンジニアの各評価項目の評価値を定期的に収集する | |

**Comment by tokoroten-lab** [comment]
# 工数見積

とりあえず正常系だけを作る工数見積を行う

## 環境構築(3:00)

| 作業 | 想定時間(hh:mm) |
| ------------- | ------------- |
| DBのDocker環境構築 | 0:30 |
| バックエンドのDocker環境構築 | 1:00 |
| フロントエンドのDocker環境構築 | 1:00 |
| docker-composeで各環境を接続 | 0:30 |

## フロントエンド(4:40)

| 実装項目 | 想定時間(hh:mm) |
| ------------- | ------------- |
| ページの遷移ができる | 0:30 |
| エンジニアのログイン(GitHubアカウントとの連携) | 1:00 |
| 人事のログイン(メールアドレス/パスワード) | 1:00 |
| サービスに登録しているエンジニア一覧を表示する | 0:30 |
| 能力を可視化したいエンジニアのリストを管理できる(追加/削除/確認) | 1:00 |
| エンジニアの総合評価値を表示する | 0:30 |
| エンジニアの各評価値(内訳)を表示する | 0:30 |
| エンジニアの各評価値の計算方法を表示する | 0:30 |
| エンジニアの各評価値から何が分かるのかを表示する | 0:20 |
| エンジニアの評価値の推移を見れるようにする | 1:00 |

## バックエンド(12:00)

| 実装項目 | 想定時間(hh:mm) |
| ------------- | ------------- |
| GitHub APIからデータを取得する | 4:00 |
| エンジニアのログイン認証 | 1:00 |
| 人事のログイン認証 | 1:00 |
| 各評価項目の評価値を計算する | 3:00 |
| 各評価値をDBに保存する | 2:00 |
| エンジニアを分析対象のリストに追加する(DBに保存) | 1:00 |
| 分析対象の全てのエンジニアの各評価項目の評価値を定期的に収集する | 2:00 |

## DB(1:30)

| 作業 | 想定時間(hh:mm) |
| ------------- | ------------- |
| スキーマの設計 | 1:00 |
| テーブル定義のSQLファイル作成&DBにロード | 0:30 |
